title: NewsClaw
description: ""
url: "https://canon-so8.github.io"
baseurl: "/trend-news"

theme: minima

plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title/

future: true
timezone: Asia/Tokyo

minima:
  skin: dark
